// Package repository contains utilities abstracting git repositories configuration
// and source code pulling
package repository

import (
	"github.com/fredjeck/configserver/internal/config"
	"time"
)

const LogKeyRepositoryName = "repository_name"

// Repository is a handle on a git repository
type Repository struct {
	Configuration *config.Repository // repository configuration
	Statistics    *Statistics        // repository access statistics
	Beholder      *Beholder          // beholder process managing the repository
}

// Statistics allows to maintain some stats about repository access
type Statistics struct {
	HitCount   int64     `json:"hitCount"`
	LastUpdate time.Time `json:"lastUpdate"`
	NextUpdate time.Time `json:"nextUpdate"`
	LastError  error     `json:"lastError"`
}

// UpdateEvent as generated by beholders
type UpdateEvent struct {
	RepositoryName string
	LastUpdate     time.Time
	NextUpdate     time.Time
	LastError      error
	Active         bool
}

// IsClientAllowed verifies if the provided clientId is allowed to access the repository based on its configuration
func (repo *Repository) IsClientAllowed(clientId string) bool {
	for _, client := range repo.Configuration.Clients {
		if client == clientId {
			return true
		}
	}
	return false
}
