name: rust-configserver
url: https://github.com/fredjeck/configserver
refreshIntervalSeconds: 10
token: abcd
checkoutLocation: /home/fred/configserver_dev/repositories/rsconfig
clients:
  - myclientid
  - sample_client